""" This file contains lists of tags. First entry is always the tag
representant and the rest are the synonyms. """

tags_001 = [
    # ???
    ('Gelatine', 'Gelatin'),
    ('Schokolade', 'Chocolate'),
    ('Speisestärke', 'Starch'),

    # Cheese/Milk/Cream
    ('Butter'),
    ('Buttermilch', 'Buttermilk'),
    ('Cheddar'),
    ('Frischkäse', 'Cream Cheese'),
    ('Gruyere '),
    ('Joghurt', 'Yogurt'),
    ('Käse', 'Cheese'),
    ('Margarine'),
    ('Milch', 'Milk'),
    ('Mozzarella'),
    ('Nutella', 'Hazelnut Cream'),
    ('Parmesan'),
    ('Quark', 'Curd'),
    ('Ricotta'),
    ('Sahne', 'Cream', 'Heavy Cream'),
    ('Saure Sahne', 'Sour Cream'),
    ('Ziegenkäse', 'Goat Cheese'),

    # Countries
    ('Amerikanisch', 'American'),
    ('Asiatisch', 'Asian'),
    ('Französisch', 'French'),
    ('Deutsch', 'German'),
    ('Englisch', 'English'),
    ('Italienisch', 'Italian'),
    ('Japanisch', 'Japanese'),
    ('Russisch', 'Russian'),
    ('Spanisch', 'Spanish'),

    # Finished
    ('Blätterteig', 'Puff Pastry'),
    ('Brot', 'Bread'),
    ('Brötchen', 'Bun'),
    ('Kekse', 'Cracker'),
    ('Löffelbiskuits', 'Sponge Finger'),
    ('Marmelade', 'Konfitüre', 'Jam'),
    ('Pastetenteig', 'Pie Crust'),
    ('Pizzateig', 'Pizza Dough'),

    # Fruits
    ('Apfel', 'Äpfel', 'Apple'),
    ('Aprikose', 'Apricot'),
    ('Avocado'),
    ('Banane', 'Banana'),
    ('Birne', 'Pear'),
    ('Brombeeren', 'Blackberry'),
    ('Dattel', 'Date'),
    ('Erdbeeren', 'Strawberry'),
    ('Feige', 'Fig'),
    ('Heidelbeeren', 'Blaubeeren', 'Blueberry'),
    ('Himbeeren', 'Raspberry'),
    ('Holunderbeeren', 'Elderberry'),
    ('Kirsche', 'Cherry'),
    ('Limette', 'Lime'),
    ('Mango'),
    ('Melone', 'Melon'),
    ('Orange'),
    ('Pfirsich', 'Peach'),
    ('Pflaumen', 'Zwetschge', 'Plum'),
    ('Quitte', 'Quince'),
    ('Rosinen', 'Korinthen', 'Raisin', 'Currants'),
    ('Trauben', 'Grapes'),
    ('Wassermelone', 'Watermelon'),
    ('Zitrone', 'Lemon'),

    # Grains/Nuts/Seeds
    ('Erdnuss', 'Peanut'),
    ('Erdnussbutter', 'Peanut Butter'),
    ('Fenchelsamen', 'Fennel Seeds'),
    ('Grieß', 'Semolina'),
    ('Haferflocken', 'Rolled Oats', 'Oats', 'Oat Flakes'),
    ('Haselnuss', 'Hazelnut'),
    ('Kokosnuss', 'Coconut'),
    ('Kokosnussmilch', 'Coconut Milk'),
    ('Kürbiskerne', 'Pumpkin Seed'),
    ('Leinsamen', 'Flax Seed'),
    ('Mandeln', 'Almond'),
    ('Marzipan'),
    ('Mohn', 'Poppy Seeds'),
    ('Müsli', 'Granola'),
    ('Pistazien', 'Pistachio'),
    ('Sesam', 'Sesame'),
    ('Sonnenblumenkerne', 'Sunflower Seed'),
    ('Walnuss', 'Walnut'),

    # Herbs
    ('Basilikum', 'Basil'),
    ('Dill'),
    ('Lavendel', 'Lavender'),
    ('Minze', 'Mint', 'Pfefferminze', 'Peppermint'),
    ('Petersilie', 'Parsley'),
    ('Rosen', 'Roses'),
    ('Salbei', 'Sage'),
    ('Schnittlauch', 'Chives'),
    ('Thymian', 'Thyme'),
    ('Zitronenmelisse', 'Balm'),

    # Meat/Fish/Egg
    ('Huhn', 'Chicken'),
    ('Eier', 'Eggs'),
    ('Eigelb', 'Eidotter', 'Egg Yolk', 'Yolk'),
    ('Eiweiß', 'Egg White'),
    ('Rind', 'Cow', 'Beef'),
    ('Schwein', 'Pork'),
    ('Speck', 'Bacon'),
    ('Würste', 'Sausages'),

    # Oil
    ('Hanföl', 'Hempseed Oil'),
    ('Olivenöl', 'Olive Oil'),
    ('Sonnenblumenöl', 'Sunflower Oil'),
    ('Walnußöl', 'Walnut Oil'),

    # Spice
    ('Agavensirup', 'Agave Nectar', 'Agave Syrup'),
    ('Ahornsirup', 'Maple Syrup'),
    ('Balsamico'),
    ('Bittermandelöl', 'Bitter Almond Oil'),
    ('Brauner Zucker', 'Brown Sugar'),
    ('Cayennepfeffer', 'Cayenne Pepper'),
    ('Essig', 'Vinegar'),
    ('Honig', 'Honey'),
    ('Kakao', 'Cocoa'),
    ('Kardamom', 'Cardamom'),
    ('Koriander', 'Cilantro'),
    ('Kreuzkümmel', 'Kumin', 'Cumin'),
    ('Kurkuma', 'Turmeric'),
    ('Zitronenschale', 'Lemon Zest'),
    ('Muskat', 'Nutmeg'),
    ('Orangenschale', 'Orange Zest'),
    ('Oregano', 'Majoran'),
    ('Paprika (Gewürz)', 'Paprika (Spice)'),
    ('Pfeffer', 'Pepper'),
    ('Piment', 'Allspice'),
    ('Puderzucker', 'Powdered Sugar'),
    ('Rosemary'),
    ('Sojasauce', 'Sojasoße', 'Soy Sauce'),
    ('Thymian', 'Thyme'),
    ('Vanille', 'Vanilla'),
    ('Zimt', 'Cinnamon'),

    # Spirits/Juice/Sirups...
    ('Amaretto'),
    ('Bier', 'Beer'),
    ('Grenadine'),
    ('Grüner Tee', 'Green Tea'),
    ('Kaffee', 'Coffee'),
    ('Kaffeelikör', 'Coffee Liqueur', 'Kahlua'),
    ('Oolong'),
    ('Rotwein', 'Red Wine'),
    ('Rum'),
    ('Rum (Dark)'),
    ('Rum (Light)'),
    ('Schnaps', 'Booze'),
    ('Schwarzer Tee', 'Black Tea'),
    ('Tee', 'Tea'),
    ('Wein', 'Wine'),
    ('Weinbrand',  'Brandy', 'Cognac', 'Armagnac'),
    ('Weißwein', 'White Wine'),

    # Vegetables
    ('Artischocke', 'Artichoke'),
    ('Bohnen', 'Beans'),
    ('Erbsen', 'Peas'),
    ('Kartoffeln', 'Potatoes'),
    ('Knoblauch', 'Garlic'),
    ('Kohl', 'Kale'),
    ('Kürbis', 'Pumpkin'),
    ('Mais', 'Corn'),
    ('Mangold', 'Chard'),
    ('Möhren', 'Mohrrüben', 'Carrot'),
    ('Oliven', 'Olives'),
    ('Paprika', 'Bell Pepper'),
    ('Pilze', 'Mushroom'),
    ('Rhabarber', 'Rhubarb'),
    ('Rübe', 'Turnip'),
    ('Schalotten', 'Shallot'),
    ('Selerie', 'Celery'),
    ('Spinat', 'Spinach'),
    ('Süßkartoffel', 'Sweet Potato'),
    ('Tofu'),
    ('Tomaten', 'Tomatoes'),
    ('Zucchini'),
    ('Zwiebeln', 'Onions'),
]