#!/usr/bin/python
# -*- coding: utf-8 -*-

""" This file contains lists of tags. First entry is always the tag
representant and the rest are the synonyms. """

tags_001 = [
    # ???
    ['Gelatine', 'Gelatin'],
    ['Hefe', 'Yeast', 'Barm'],
    ['Schokolade', 'Chocolate'],
    ['Semmelbrösel', 'Bread Crumbs', 'Panko Crumbs'],
    ['Speisestärke', 'Starch'],

    # Cheese/Milk/Cream
    ['Brie'],
    ['Butter'],
    ['Buttermilch', 'Buttermilk'],
    ['Cheddar'],
    ['Feta'],
    ['Frischkäse', 'Cream Cheese'],
    ['Gorgonzola'],
    ['Gruyere '],
    ['Joghurt', 'Yogurt'],
    ['Käse', 'Cheese'],
    ['Margarine'],
    ['Mascarpone'],
    ['Milch', 'Milk'],
    ['Mozzarella'],
    ['Nutella', 'Hazelnut Cream'],
    ['Parmesan'],
    ['Quark', 'Curd'],
    ['Ricotta'],
    ['Sahne', 'Rahm', 'Cream', 'Heavy Cream'],
    ['Saure Sahne', 'Sour Cream'],
    ['Sojamilch', 'Soy Milk'],
    ['Ziegenkäse', 'Goat Cheese'],

    # Countries
    ['Amerikanisch', 'American'],
    ['Asiatisch', 'Asian'],
    ['Französisch', 'French'],
    ['Deutsch', 'German'],
    ['Englisch', 'English'],
    ['Italienisch', 'Italian'],
    ['Japanisch', 'Japanese'],
    ['Mexikanisch', 'Mexican'],
    ['Russisch', 'Russian'],
    ['Spanisch', 'Spanish'],
    
    # Finished
    ['Baguette'],
    ['Blätterteig', 'Puff Pastry'],
    ['Brot', 'Bread'],
    ['Brötchen', 'Bun'],
    ['Eiscreme', 'Speiseeis', 'Ice Cream'],
    ['Fladen', 'Flatbreads', 'Pita'],
    ['Gnocchi'],
    ['Kekse', 'Cracker'],
    ['Lasagneplatten', 'Lasagna Sheets', 'Lasagna Noodles'],
    ['Löffelbiskuits', 'Sponge Finger'],
    ['Marmelade', 'Konfitüre', 'Jam'],
    ['Miso'],
    ['Nudeln', 'Pasta'],
    ['Pastetenteig', 'Pie Crust'],
    ['Pesto'],
    ['Pizzateig', 'Pizza Dough'],
    ['Toast'],
    ['Tortellini'],
    ['Tortillas'],

    # Fruits
    ['Apfel', 'Äpfel', 'Apple'],
    ['Aprikose', 'Apricot'],
    ['Ananas', 'Pineapple'],
    ['Avocado'],
    ['Banane', 'Banana'],
    ['Berberitzen', 'Barberry'],
    ['Birne', 'Pear'],
    ['Brombeeren', 'Blackberry'],
    ['Cranberry'],
    ['Dattel', 'Date'],
    ['Erdbeeren', 'Strawberry'],
    ['Feige', 'Fig'],
    ['Grapefrucht', 'Grapefruit'],
    ['Heidelbeeren', 'Blaubeeren', 'Blueberry'],
    ['Himbeeren', 'Raspberry'],
    ['Holunderbeeren', 'Elderberry'],
    ['Honigmelone', 'Rock Melon', 'Honeydew Melon'],
    ['Johannisbeeren', 'Currant'],
    ['Kirsche', 'Cherry'],
    ['Kiwi'],
    ['Kumquat'],
    ['Limette', 'Lime'],
    ['Mandarine', 'Mandarin'],
    ['Mango'],
    ['Melone', 'Melon'],
    ['Maracuja', 'Passionsfrucht', 'Passion Fruit'],
    ['Nektarine', 'Nectarine'],
    ['Orange'],
    ['Pfirsich', 'Peach'],
    ['Pflaumen', 'Zwetschge', 'Plum', 'Prune'],
    ['Preiselbeeren', 'Cowberry', 'Lingonberry', 'Lowbush Cranberry', 'Mountain Cranberry'],
    ['Quitte', 'Quince'],
    ['Rosinen', 'Korinthen', 'Raisin', 'Currants'],
    ['Trauben', 'Grapes'],
    ['Wassermelone', 'Watermelon'],
    ['Zitrone', 'Lemon'],

    # Grains/Nuts/Seeds
    ['Cashew'],
    ['Chia'],
    ['Couscous', 'Kuskus'],
    ['Erdnuss', 'Peanut'],
    ['Erdnussbutter', 'Peanut Butter'],
    ['Fenchelsamen', 'Fennel Seeds'],
    ['Grieß', 'Semolina'],
    ['Haferflocken', 'Rolled Oats', 'Oats', 'Oat Flakes'],
    ['Haselnuss', 'Hazelnut'],
    ['Kokosnuss', 'Coconut'],
    ['Kokosnussmilch', 'Kokosmilch', 'Coconut Milk', 'Creme De Coconut', 'Cream Of Coconut'],
    ['Kürbiskerne', 'Pumpkin Seed', 'Pepita'],
    ['Leinsamen', 'Flax Seed'],
    ['Maismehl', 'Cornmeal'],
    ['Mandeln', 'Almond'],
    ['Marzipan'],
    ['Mehl', 'Flour'],
    ['Milchreis', 'Rice Pudding'],
    ['Mohn', 'Poppy Seeds'],
    ['Müsli', 'Granola'],
    ['Nüsse', 'Nuss', 'Nuts'],
    ['Pekannuss', 'Pecan'],
    ['Pinienkerne', 'Pine Nut', 'Pignolia'],
    ['Pistazien', 'Pistachio'],
    ['Polenta'],
    ['Reis', 'Rice'],
    ['Sesam', 'Sesame'],
    ['Sonnenblumenkerne', 'Sunflower Seed'],
    ['Walnuss', 'Walnut'],

    # Herbs
    ['Bärlauch', 'Bear\'s Garlic', 'Ramsons'],
    ['Basilikum', 'Basil'],
    ['Dill'],
    ['Lavendel', 'Lavender'],
    ['Minze', 'Mint', 'Pfefferminze', 'Peppermint'],
    ['Kresse', 'Cress'],
    ['Petersilie', 'Parsley'],
    ['Rosen', 'Roses'],
    ['Salbei', 'Sage'],
    ['Schnittlauch', 'Chives'],
    ['Thymian', 'Thyme'],
    ['Zitronenmelisse', 'Balm'],
    
    # Meat/Fish/Egg
    ['Corned Beef'],
    ['Huhn', 'Chicken'],
    ['Eier', 'Eggs'],
    ['Eigelb', 'Eidotter', 'Egg Yolk', 'Yolk'],
    ['Eiweiß', 'Egg White'],
    ['Ente', 'Duck'],
    ['Fisch', 'Fish'],
    ['Garnelen', 'Shrimps', 'Prawn'],
    ['Hackfleisch', 'Hash', 'Minced Meat', 'Ground Meat'],
    ['Krebs', 'Languste', 'Crawfish'],
    ['Lachs', 'Salmon'],
    ['Lamm', 'Lamb'],
    ['Rind', 'Cow', 'Beef'],
    ['Schwein', 'Pork'],
    ['Schinken', 'Ham', 'Prosciutto'],
    ['Speck', 'Bacon', 'Pancetta'],
    ['Thunfisch', 'Tuna'],
    ['Tilapia'],
    ['Truthahn', 'Turkey'],
    ['Wild', 'Venison'],
    ['Wildschwein', 'Boar'],
    ['Würste', 'Wurst', 'Sausage'],

    # Oil
    ['Hanföl', 'Hempseed Oil'],
    ['Olivenöl', 'Olive Oil'],
    ['Rapsöl', 'Canola Oil'],
    ['Sonnenblumenöl', 'Sunflower Oil'],
    ['Walnussöl', 'Walnut Oil'],

    # Spice
    ['Agavensirup', 'Agave Nectar', 'Agave Syrup'],
    ['Ahornsirup', 'Maple Syrup'],
    ['Anis', 'Anise'],
    ['Aubergine', 'Eggplant'],
    ['Balsamico', 'Balsamic Vinegar'],
    ['Bittermandelöl', 'Bitter Almond Oil'],
    ['Bohnenkraut', 'Savory'],
    ['Brauner Zucker', 'Brown Sugar'],
    ['Cayennepfeffer', 'Cayenne Pepper'],
    ['Chilisauce', 'Hot Sauce'],
    ['Curry'],
    ['Essig', 'Vinegar'],
    ['Estragon', 'Tarragon'],
    ['Honig', 'Honey'],
    ['Ingwer', 'Ginger'],
    ['Kakao', 'Cocoa'],
    ['Kardamom', 'Cardamom'],
    ['Ketchup'],
    ['Koriander', 'Coriander', 'Cilantro'],
    ['Kreuzkümmel', 'Kumin', 'Cumin'],
    ['Kurkuma', 'Turmeric'],
    ['Lorbeerblätter', 'Bay Leaves'],
    ['Mayonnaise', 'Mayo'],
    ['Muskat', 'Nutmeg'],
    ['Nelken', 'Clove'],
    ['Orangenschale', 'Orange Zest'],
    ['Oregano', 'Majoran'],
    ['Paprika [Gewürz]', 'Paprika [Spice]'],
    ['Pfeffer', 'Pepper'],
    ['Piment', 'Allspice'],
    ['Puderzucker', 'Powdered Sugar'],
    ['Reisessig', 'Rice Vinegar'],
    ['Rosmarin', 'Rosemary'],
    ['Salz', 'Salt'],
    ['Senf', 'Mustard'],
    ['Sriracha'],
    ['Sojasauce', 'Sojasoße', 'Soy Sauce'],
    ['Vanille', 'Vanilla'],
    ['Wacholderbeeren', 'Juniper Berry'],
    ['Wasabi'],
    ['Worcestershiresauce', 'Worcestersauce ' 'Worcestershire Sauce'],
    ['Zimt', 'Cinnamon'],
    ['Zitronenschale', 'Lemon Zest'],
    ['Zucker', 'Sugar'],

    # Spirits/Juice/Sirups...
    ['Amaretto'],
    ['Ananassaft', 'Pineapple Juice'],
    ['Apfelsaft', 'Apple Juice'],
    ['Bier', 'Beer', 'Ale', 'Stout'],
    ['Bitter'],
    ['Bourbon Whiskey', 'Rye Whiskey'],
    ['Cachaça', 'Cachaca'],
    ['Calvados'],
    ['Chartreuse'],
    ['Cola'],
    ['Cranberry Saft', 'Cranberry Juice'],
    ['Curaçao', 'Curacao'],
    ['Fanta'],
    ['Gin'],
    ['Ginger Ale'],
    ['Ginger Beer'],
    ['Grapefruchtsaft', 'Grapefruit Juice'],
    ['Grenadine'],
    ['Grüner Tee', 'Green Tea'],
    ['Himbeersaft', 'Raspberry Juice'],
    ['Irish Cream', 'Bailey\'s Irish Cream'],
    ['Irish Whiskey'],
    ['Kaffee', 'Coffee', 'Espresso'],
    ['Kaffeelikör', 'Coffee Liqueur', 'Kahlua'],
    ['Kräuterlikör', 'Herbal Liqueur'],
    ['Kornbrand', 'Korn'],
    ['Lavendel Sirup', 'Lavender Syrup'],
    ['Limonade', 'Lemonade'],
    ['Mandelsirup', 'Almond Syrup', 'Orgeat Syrup'],
    ['Mineralwasser', 'Club Soda', 'Soda Water'],
    ['Oolong'],
    ['Orangen Bitter', 'Orange Bitter'],
    ['Orangenlikör', 'Orange Liqueur', 'Grand Marnier', 'Triple Sec', 'Cointreau'],
    ['Orangensaft', 'Orange Juice'],
    ['Pfirsich Likör', 'Peach Liqueur'],
    ['Pfirsichsirup', 'Peach Syrup'],
    ['Rosmarin Sirup', 'Rosemary Syrup'],
    ['Rotwein', 'Red Wine'],
    ['Rum'],
    ['Rum [Dark]'],
    ['Rum [Light]'],
    ['Saffron'],
    ['Schnaps', 'Booze'],
    ['Schwarzer Tee', 'Black Tea'],
    ['Scotch Whisky'],
    ['Sekt', 'Champagne', 'Sparkling Wine'],
    ['Sour Mix'],
    ['Tee', 'Tea'],
    ['Tequila'],
    ['Tomatensaft', 'Tomato Juice'],
    ['Tonic Water'],
    ['Vermouth [Dry'],
    ['Vermouth [Sweet]'],
    ['Vodka'],
    ['Wein', 'Wine'],
    ['Weinbrand',  'Brandy', 'Cognac', 'Armagnac'],
    ['Weißwein', 'White Wine'],
    ['Whisky', 'Whiskey'],
    ['Zimt Sirup', 'Cinnamon Syrup'],
    ['Zuckersirup', 'Simple Syrup', 'Sugar Syrup'],

    # Vegetables
    ['Anschovis', 'Anchovis', 'Anchovy'],
    ['Artischocke', 'Artichoke'],
    ['Blumenkohl', 'Cauliflower'],
    ['Bohnen', 'Beans'],
    ['Brokkoli', 'Broccoli'],
    ['Chicoree', 'Chicory'],
    ['Chili', 'Chilli', 'Peperoni'],
    ['Erbsen', 'Peas'],
    ['Fenchel', 'Fennel'],
    ['Gurke', 'Cucumber'],
    ['Kapern', 'Capers'],
    ['Kartoffeln', 'Potatoes'],
    ['Kichererbsen', 'Chickpea'],
    ['Knoblauch', 'Garlic'],
    ['Kohl', 'Kale', 'Cabbage'],
    ['Kohlrabi', 'Cabbage Turnip'],
    ['Kürbis', 'Pumpkin', 'Squash'],
    ['Lauch', 'Porree', 'Leek', 'Ramp'],
    ['Linsen', 'Lentils'],
    ['Mais', 'Corn'],
    ['Mangold', 'Chard'],
    ['Meerrettich', 'Horseradish'],
    ['Möhren', 'Mohrrüben', 'Karotten', 'Carrot'],
    ['Noriblätter', 'Nori'],
    ['Oliven', 'Olives'],
    ['Paprika', 'Bell Pepper'],
    ['Pilze', 'Mushroom'],
    ['Rettich', 'Radish'],
    ['Rhabarber', 'Rhubarb'],
    ['Rübe', 'Turnip'],
    ['Rucola', 'Arugula'],
    ['Salat', 'Lettuce'],
    ['Schalotten', 'Shallot', 'Scallions'],
    ['Sellerie', 'Celery'],
    ['Spargel', 'Asparagus'],
    ['Spinat', 'Spinach'],
    ['Süßkartoffel', 'Sweet Potato'],
    ['Tofu'],
    ['Tomaten', 'Tomatoes'],
    ['Zucchini', 'Courgette'],
    ['Zwiebeln', 'Onions'],
]

tags_002 = [
    #['Französisch', 'French'],
    #['Deutsch', 'German'],
    #['Englisch', 'English'],
    #['Italienisch', 'Italian'],
    #['Japanisch', 'Japanese'],
    #['Mexikanisch', 'Mexican'],
    #['Russisch', 'Russian'],
    #['Spanisch', 'Spanish'],

    # Countries
    ['Afghanisch', 'Afghan'],
    ['Afrikanisch', 'Afrikanisch'],
    ['Albanisch', 'Albanian'],
    ['Algerisch', 'Algerian'],
    #['Amerikanisch', 'American'],
    ['Andorranisch', 'Andorran'],
    ['Angolanisch', 'Angolian'],
    ['Antiguanisch', 'Antiguan'],
    ['Argentinisch', 'Argentinean'],
    ['Armenisch', 'Armenian'],
    #['Asiatisch', 'Asian'],
    ['Australisch', 'Australian'],
    ['Aserbaidschanisch', 'Azerbaijanian'],
    ['Bahamaisch', 'Bahamian'],
    ['Bahrainisch', 'Bahraini'],
    ['Bangladeschisch', 'Bangladeshi'],
    ['Barbadisch', 'Barbadian'],
    ['Belorussisch', 'Byelorussian', 'Byelorussian'],
    ['Belgisch', 'Belgian'],
    ['Belizisch', 'Belizean'],
    ['Beninisch', 'Beninese'],
    ['Bhutanisch', 'Bhutanese'],
    ['Bolivianisch', 'Bolivian'],
    ['Bosnisch', 'Bosnian'],
    ['Botsuanisch', 'Botsuanisch', 'Botswanian'],
    ['Brasilianisch', 'Brazilian'],
    ['Bruneiisch', 'Bruneian'],
    ['Bulgarisch', 'Bulgarian'],
    ['Burkinisch', 'Burkinabe'],
    ['Burmesisch', 'Burmese'],
    ['Burundisch', 'Burundian'],
    ['', ''],
    ['', ''],
    ['Europäisch', 'European'],
    ['', ''],
    ['Österreichisch', 'Austrian'],
    ['', ''],
]